### ISSUE TITLE
The new row count checking (or logical replication?) isn't quite working as intended

### ISSUE THREAD

**Issue by johto** [trustly/pg_trivialreplay#2]
Here's an excerpt from the log:

```
pg_trivialreplay: confirming write up to 234/77062E08, flush to 234/77062E08 (slot nineone)
pg_trivialreplay: confirming write up to 234/77062E08, flush to 234/77062E08 (slot nineone)
pg_trivialreplay: replay of 'UPDATE [ .. ]' processed 0 rows, not 1!
pg_trivialreplay: replay of 'UPDATE [ .. ]' processed 0 rows, not 1!
pg_trivialreplay: confirming write up to 234/77094B20, flush to 234/77094B20 (slot nineone)
```

So it looks like trivialreplay knows that something's wrong but continues regardless (after having simply skipped the UPDATEs which didn't match any rows).

I didn't spend too much time debugging, but [this](https://github.com/trustly/pg_trivialreplay/blob/ab1947f752c11b7ba4435b0916ca2167b1605f9d/pg_trivialreplay.c#L528) looks suspicious -- surely we don't want to ACK anything before we've written it to the target database.

**Comment by mhagander** [comment]
For one, should it not just exit() with an error after it detects a problem with the UPDATE?

I think the sendFeedback() call is correct -- it will use output_written_lsn and output_fsync_lsn, and we don't update output_fsync_lsn until after we've run COMMIT and it succeeded.

Is that a log excerpt without cuts? As I read the code after the "replay of..." failure, it should exit StreamLogicalLog(), at which point it should loop up and try again, but there should also be a message about "starting log streaming at" when it gets a new connection.

Also, how did we end up with *two* errors of "replay of" type. Shouldn't [this](https://github.com/trustly/pg_trivialreplay/blob/ab1947f752c11b7ba4435b0916ca2167b1605f9d/pg_trivialreplay.c#L653) prevent that?

To me that output almost looks as there were *two* instances of pg_trivialreplay running, but surely it's not that?

**Comment by mhagander** [comment]
I should add -- do you have an (easily) reproducible testcase to provoke this, or is it something that showed up once and not again?

**Comment by johto** [comment]
> To me that output almost looks as there were two instances of pg_trivialreplay running, but surely it's not that?

I hope not.

> Is that a log excerpt without cuts? As I read the code after the "replay of..." failure, it should exit StreamLogicalLog(), at which point it should loop up and try again, but there should also be a message about "starting log streaming at" when it gets a new connection.

I might have cut parts of the log out.  I'm not sure anymore.

> I should add -- do you have an (easily) reproducible testcase to provoke this, or is it something that showed up once and not again?

It showed up until I fixed the postgres bug that caused it :-P  I didn't spend any time on this aside from quickly typing up this issue because I wanted to test the thing when it works.

**Comment by mhagander** [comment]
This seems to have worked fine during the testing today. This must either have been fixed as a side-effect of the other changes since, or there really was something like it running twice on the same slot.

Closing this one for now, as we really don't have enough data to debug it further.
