### ISSUE TITLE
Transaction batch size

### ISSUE THREAD

**Issue by johto** [trustly/pg_trivialreplay#3]
Since we're not running in synchronous mode, we should probably allow batches of transactions to be committed on the target system instead of matching transactions 1:1.

**Comment by mhagander** [comment]
You mean basically collect up to <n> commits before we update the target location and commit them together?

That would work, but maybe we would reach almost the same performance by just setting synchronous_comit='off' and keeping the logic simpler, the way it is now?

**Comment by johto** [comment]
On 2016-08-19 10:50, Magnus Hagander wrote:
> You mean basically collect up to <n> commits before we update the target location and commit them together?

Yup.

> That would work, but maybe we would reach almost the same performance by just setting synchronous_comit='off' and keeping the logic simpler, the way it is now?

I tried that; synchronous_commit didn't help much.


.m

**Comment by mhagander** [comment]
This was implemented by #8.
